apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-storage-classes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/c-chandran/eks-gitops-lab
    targetRevision: HEAD
    path: apps/ceph-storage-classes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
