apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/eks-lab-argocd.git
    targetRevision: bootstrap
    path: apps/kubecost-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
