apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/eks-lab-argocd.git
    targetRevision: bootstrap
    path: apps/nginx-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
