apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-test
  template:
    metadata:
      labels:
        app: ceph-test
    spec:
      containers:
      - name: test-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ceph-storage
          mountPath: /data
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date) >> /data/test.log; sleep 30; done"]
      volumes:
      - name: ceph-storage
        persistentVolumeClaim:
          claimName: ceph-test-pvc
