{
 "title": "AWS - EKS",
 "description": "This dashboard shows Container Insight metrics for EKS via CloudWatch.",
 "tags": [
  "auto",
  "aws",
  "eks"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" }
  ]
 },
 "panels": [
  { "title": "EKS (Summary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "cluster_node_count",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_number_of_running_pods",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_number_of_running_containers",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Nodes - Max Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_network_total_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Nodes - Max Filesystem Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_filesystem_utilization",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Pods - Max Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_network_tx_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Pods - Max Bytes Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_network_rx_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_number_of_container_restarts",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Nodes - Total Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_network_total_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pods - Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_network_tx_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Pods - Total Bytes Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_network_rx_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Current Node CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_cpu_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Node Mem %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_memory_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Pod CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_cpu_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Pod Mem %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_memory_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "EKS (Historical)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Node Utilization %'s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_cpu_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_memory_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Node Utilization %'s (by IP)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd", "NodeName": "*" },
     "label": "${PROP('Dim.NodeName')}",
     "metricName": "node_cpu_utilization",
     "namespace": "ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Node Network Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "label": "${PROP('Dim.NodeName')}",
     "metricName": "node_network_total_bytes",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pods - Historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_number_of_running_pods",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "pod_number_of_container_restarts",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Containers - Historical",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dimensions": { "ClusterName": "eks-lab-argocd" },
     "metricName": "node_number_of_running_containers",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "EKS (Additional Alerts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "dimensions": { "ClusterName": "eks-lab-argocd" },
       "metricName": "pod_number_of_container_restarts",
       "namespace": "ContainerInsights",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Average Filesystem Utilization - By Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "eks-lab-argocd", "NodeName": "*" },
       "metricName": "node_filesystem_utilization",
       "namespace": "ContainerInsights",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "EKS (Logs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "[EKS Cluster Logs] - ${datasource}",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 100",
       "logGroups": [
        {
         "accountId": "432801802107",
         "arn": "arn:aws:logs:eu-central-1:432801802107:log-group:/aws/eks/eks-lab-argocd/cluster:*",
         "name": "/aws/eks/eks-lab-argocd/cluster"
        }
       ],
       "namespace": "AWS/AppRunner",
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "[Fluentbit Cloudwatch Logs] -  ${datasource}",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
       "logGroups": [
        {
         "accountId": "432801802107",
         "arn": "arn:aws:logs:eu-central-1:432801802107:log-group:/aws/containerinsights/eks-lab-argocd/application:*",
         "name": "/aws/containerinsights/eks-lab-argocd/application"
        }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 - Error Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "metricName": "4xxErrors",
       "namespace": "AWS/S3",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "5xxErrors",
       "namespace": "AWS/S3",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "S3 - Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "metricName": "TotalRequestLatency",
       "namespace": "AWS/S3",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "ReplicationLatency",
       "namespace": "AWS/S3",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "FirstByteLatency",
       "namespace": "AWS/S3",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloudfront",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "CloudFront Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 49 },
     "targets": [
      {
       "metricName": "Requests",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CloudFront Error Rates (by Range)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 49 },
     "targets": [
      {
       "metricName": "4xxErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "5xxErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CloudFront Error Rates (by Code)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "metricName": "401ErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "403ErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "404ErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "502ErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "503ErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "504ErrorRate",
       "namespace": "AWS/CloudFront",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "SQS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQS Messages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "metricName": "NumberOfMessagesSent",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "NumberOfMessagesReceived",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "metricName": "NumberOfMessagesDeleted",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Secrets Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 30 },
     "targets": [
      { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
     ]
    }
   ]
  }
 ]
}