apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: eks-lab-argocd-node-group-role
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-lab-argocd
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-lab-argocd
  metadataOptions:
    httpPutResponseHopLimit: 2
  userData: |
    ---
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      cluster:
        name: eks-lab-argocd
        apiServerEndpoint: {{ .ClusterEndpoint }}
        certificateAuthority: {{ .ClusterCA }}
        cidr: {{ .ClusterCIDR }}
