apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-05f37490159649552
  role: eks-lab-argocd-node-group-role
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-lab-argocd
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-lab-argocd
  metadataOptions:
    httpPutResponseHopLimit: 2
